force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <label>Medical Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Doctor that will conduct the Appointment.</description>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>&quot;Doctor&quot;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Medical Facility at which our Appointment will take place.</description>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Patient that will attend to the Appointment.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>&quot;Patient&quot;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Patient)</relationshipLabel>
    <relationshipName>Medical_Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Surgery__c.field-meta.xml
<CustomField>
    <fullName>Surgery__c</fullName>
    <description>Number of the room at whitch appointment in the facility takes place</description>
    <label>Surgery</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/recordTypes/Online.recordType-meta.xml
<RecordType>
    <fullName>Online</fullName>
    <active>true</active>
    <label>Online</label>
</RecordType>

force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Insurance_required__c.field-meta.xml
<CustomField>
    <fullName>Insurance_required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This facility accepts only patients that are insured.</description>
    <label>Insurance required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medical_Insurance__c/Medical_Insurance__c.object-meta.xml
<CustomObject>
    <label>Medical Insurance</label>
    <nameField>
        <label>Medical Insurance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical_Insurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Insurance__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <description>Facilities that covers our insurance.</description>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical_Insurances</relationshipLabel>
    <relationshipName>Medical_Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Medical_Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person&apos;s Medical Incurance</description>
    <label>Medical Insurance</label>
    <referenceTo>Medical_Insurance__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Personal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Personal_ID_Number__c</fullName>
    <description>PESEL number</description>
    <label>Personal ID Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Hematology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Orthopedics</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Pulmonology</fullName>
            </value>
            <value>
                <fullName>Rheumatology</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Obstetrics &amp; Gynecology</fullName>
            </value>
            <value>
                <fullName>Allergy &amp; Immunology</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Emergency Medicine</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Physical Medicine &amp; Rehabilitation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <label>Patient</label>
</RecordType>

force-app/main/default/classes/MedicalAppointmentHandler.cls
public with sharing class MedicalAppointmentHandler {
   
   
    public static void handleUpdateOrNewAppointment(List<Medical_Appointment__c> newAppointments, Map<Id, Medical_Appointment__c> oldAppointmentsMap, Boolean isInsert, Boolean isUpdate) {
      Set<String> patientPersonalIDs = new Set<String>();
  
      for (Medical_Appointment__c appointment : newAppointments) {
          patientPersonalIDs.add(appointment.Patient__c);
      }
      
      Map<String, Person__c> patientDetails = new Map<String, Person__c>();
      
      List<Person__c> listOfPatients =  [SELECT Email__c, Personal_ID_Number__c, First_Name__c, LastName__c FROM Person__c WHERE Id IN :patientPersonalIDs];
  
      for(Person__c person : listOfPatients) {
          patientDetails.put(person.Id, person);
      }
  
      List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
      
      for (Medical_Appointment__c appointment : newAppointments) {
          Person__c patient = patientDetails.get(appointment.Patient__c);
          if(isUpdate){
              Medical_Appointment__c oldPatient = oldAppointmentsMap.get(appointment.Id);
          
          if (patient != null && patient.Email__c != null && oldPatient != null) {
              if(appointment.Appointment_Date__c != oldPatient.Appointment_Date__c || 
              appointment.Status__c != oldPatient.Status__c || 
              appointment.Surgery__c != oldPatient.Surgery__c || 
              appointment.RecordTypeId != oldPatient.RecordTypeId){
                  
                Messaging.SingleEmailMessage mail = EmailMessageBuilder.createEmailMessage(appointment, patient);
                  emails.add(mail);
               }
              }
          }
          if(isInsert){
            Messaging.SingleEmailMessage mail = EmailMessageBuilder.createEmailMessage(appointment, patient);
            emails.add(mail);
          }
          
      }
      
      if(!emails.isEmpty()){
          Messaging.sendEmail(emails);
      }
  }

  public static void handleFirstInternistAppointmentONSITE(List<Medical_Appointment__c> newAppointment){
      List<Id> patientPersonalIDs = new List<Id>();
      Map<Id, Medical_Appointment__c> appointmentList = new Map<Id, Medical_Appointment__c> ();
      List<Id> usedIds = new List<Id>();
      List<Id> doctorPersonalIDs = new List<Id>();
  
      for(Medical_Appointment__c app : newAppointment){
          Id getInfo = Schema.getGlobalDescribe()
          .get('Medical_Appointment__c')
          .getDescribe()
          .getRecordTypeInfosByName()
          .get('Online')
          .getRecordTypeId();
          if(app.RecordTypeId == getInfo){
              appointmentList.put(app.id, app);
              patientPersonalIDs.add(app.Patient__c);
          }
      }
  
      List<Person__c> doctorsList = [SELECT Id FROM Person__c WHERE Specialization__c = 'Internist'];
      for(Person__c doc : doctorsList){
          doctorPersonalIDs.add(doc.Id);
      }
      
      List<Medical_Appointment__c> used = [SELECT Patient__c FROM Medical_Appointment__c WHERE Doctor__c IN :doctorPersonalIDs AND Patient__c IN :patientPersonalIDs];
      for(Medical_Appointment__c i : used){
          usedIds.add(i.Patient__c);
      }
  
      for (Medical_Appointment__c i : appointmentList.values()) {
          if(!usedIds.contains(i.Patient__c) && doctorPersonalIDs.contains(i.Doctor__c)){
              i.addError('First Internists Visit must be "On Site"');
          }
      }
  }


  public static void handleInsuranceRequired(List<Medical_Appointment__c> newAppointment){
      List<Medical_Appointment__c> appointmentsWithInsurance = newAppointment;
      Set<Id> medicalFacilitiesIds = new Set<Id>();
      Set<Id> patientsIds = new Set<Id>();
      for(Medical_Appointment__c appointment : appointmentsWithInsurance) {
          patientsIds.add(appointment.Patient__c);
          medicalFacilitiesIds.add(appointment.Medical_Facility__c);
      }
      Map<Id, Medical_Facility__c> facilityMap = new Map<Id, Medical_Facility__c>([SELECT Id, Insurance_required__c FROM Medical_Facility__c WHERE Id IN :medicalFacilitiesIds]);
      Map<Id, Medical_Facility__c> appointmentFacility = new Map<Id, Medical_Facility__c>();
      for(Medical_Appointment__c appointment : appointmentsWithInsurance) {
          appointmentFacility.put(appointment.Id, facilityMap.get(appointment.Medical_Facility__c));
      }
      Map<Id, Person__c> patientMap = new Map<Id, Person__c>([SELECT Id, Medical_insurance__c FROM Person__c WHERE Id IN :patientsIds]);
      
      for(Medical_Appointment__c appointment : appointmentsWithInsurance) {
          Person__c patient = patientMap.get(appointment.Patient__c);
          Medical_Facility__c facility = appointmentFacility.get(appointment.Id);
          if (patient.Medical_insurance__c == null&&
          facility.Insurance_required__c==true) {
              appointment.addError('Insurance is required for this appointment');
          }           
      }
  }

}