force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours__c</fullName>
    <label>Operating_Hours__c</label>
    <referenceTo>Operating_Hours__c</referenceTo>
    <relationshipLabel>Medical Facilitys</relationshipLabel>
    <relationshipName>Medical_Facilitys</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/Operating_Hours__c.object-meta.xml
<CustomObject>
    <label>Operating Hours</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Operating Hours Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Hours__c/fields/Closing_Time__c.field-meta.xml
<CustomField>
    <fullName>Closing_Time__c</fullName>
    <label>Closing Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Operating Hours</relationshipLabel>
    <relationshipName>Operating_Hours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Opening_Time__c.field-meta.xml
<CustomField>
    <fullName>Opening_Time__c</fullName>
    <label>Opening Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Week_Day__c.field-meta.xml
<CustomField>
    <fullName>Week_Day__c</fullName>
    <label>Week Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpeningHoursController.cls
public with sharing class OpeningHoursController {
    @AuraEnabled(cacheable=true)
    public static List<Operating_Hours__c> getHours(Id facilityId) {
        List<Operating_Hours__c> hours = [SELECT Id, Closing_Time__c, Week_Day__c, Opening_Time__c FROM Operating_Hours__c WHERE Medical_Facility__c = :facilityId];
        List<Operating_Hours__c> sortedHours = new List<Operating_Hours__c>();
        List<String> days = new List<String>{'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'};
        for (String day : days) {
            for(Operating_Hours__c hour : hours) {
                if(hour.Week_Day__c == day) {
                    sortedHours.add(hour);
                    break;
                }
            }
        }
        return sortedHours;
    }
}