force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours__c</fullName>
    <label>Operating_Hours__c</label>
    <referenceTo>Operating_Hours__c</referenceTo>
    <relationshipLabel>Medical Facilitys</relationshipLabel>
    <relationshipName>Medical_Facilitys</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/Operating_Hours__c.object-meta.xml
<CustomObject>
    <label>Operating Hours</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Operating Hours Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Hours__c/fields/Closing_Time__c.field-meta.xml
<CustomField>
    <fullName>Closing_Time__c</fullName>
    <label>Closing Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Operating Hours</relationshipLabel>
    <relationshipName>Operating_Hours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Opening_Time__c.field-meta.xml
<CustomField>
    <fullName>Opening_Time__c</fullName>
    <label>Opening Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Hematology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Orthopedics</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Pulmonology</fullName>
            </value>
            <value>
                <fullName>Rheumatology</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Obstetrics &amp; Gynecology</fullName>
            </value>
            <value>
                <fullName>Allergy &amp; Immunology</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Emergency Medicine</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Physical Medicine &amp; Rehabilitation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/classes/AppointmentController.cls
public with sharing class AppointmentController {
    @AuraEnabled(cacheable=true)
    public static List<Person__c> getDoctorsBySpecialization(String specialization) {
        return [SELECT Id, First_Name__c, LastName__c, Specialization__c, Medical_Facility__r.Name
                FROM Person__c
                WHERE RecordType.Name = 'Doctor' AND Specialization__c = :specialization
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getSpecializations() {
        List<AggregateResult> tmp = [SELECT Specialization__c FROM Person__c WHERE RecordType.Name = 'Doctor' GROUP BY Specialization__c];

        List<String> specializationsList = new List<String>();

        for (AggregateResult p : tmp) {
            specializationsList.add((String)p.get('Specialization__c'));
        }

        return specializationsList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Operating_Hours__c> getHours(String selectedDay, Id selectedFacility) {
        return [SELECT Opening_Time__c, Closing_Time__c 
                FROM Operating_Hours__c 
                WHERE Day_of_Week__c = :selectedDay AND Medical_Facility__c = :selectedFacility
        ];
    }
}