force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Doctors_List__c.field-meta.xml
<CustomField>
    <fullName>Doctors_List__c</fullName>
    <description>A list of Doctors in Medical Facility</description>
    <label>Doctors List</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Facilitys</relationshipLabel>
    <relationshipName>Medical_Facilitys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>Flat_Number__c</fullName>
    <label>Flat Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours__c</fullName>
    <label>Operating_Hours__c</label>
    <referenceTo>Operating_Hours__c</referenceTo>
    <relationshipLabel>Medical Facilitys</relationshipLabel>
    <relationshipName>Medical_Facilitys</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/Operating_Hours__c.object-meta.xml
<CustomObject>
    <label>Operating Hours</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Operating Hours Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operating_Hours__c/fields/Closing_Time__c.field-meta.xml
<CustomField>
    <fullName>Closing_Time__c</fullName>
    <label>Closing Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Operating Hours</relationshipLabel>
    <relationshipName>Operating_Hours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operating_Hours__c/fields/Opening_Time__c.field-meta.xml
<CustomField>
    <fullName>Opening_Time__c</fullName>
    <label>Opening Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>Flat_Number__c</fullName>
    <label>Flat Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FacilityWorkingHoursUpdateTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class FacilityWorkingHoursUpdateTest {
    @TestSetup
    static void makeData(){
        Person__c person = new Person__c(
            First_Name__c = 'Jan',
            LastName__c = 'Kowalski'
        );
        insert person;

        Medical_Facility__c f = new Medical_Facility__c(
            Name = 'Facility 1',
            City__c = 'Lodz',
            Flat_Number__c = 11,
            Postcode__c = '00-000',
            Street_Name__c = 'Aleje Politechniki',
            Street_Number__c = 111,
            Doctors_List__c = person.Id
        );

        insert f;

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Monday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Tuesday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Wednesday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Thursday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Friday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Saturday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );

        insert new Operating_Hours__c(
            Day_of_Week__c = 'Sunday',
            Opening_Time__c = Time.newInstance(8, 0, 0, 0),
            Closing_Time__c = Time.newInstance(16, 0, 0, 0),
            Medical_Facility__c = f.Id
        );
    }

    @isTest
    static void testScheduleMe() {
        Test.startTest();
        Id jobId = FacilityWorkingHoursUpdate.scheduleMe('Test Job');
        Test.stopTest();

        System.assertNotEquals(null, jobId);
    }

    @isTest
    static void testUpdateHoursRandomly() {
        List<Operating_Hours__c> Hours = [SELECT Id, Opening_Time__c, Closing_Time__c FROM Operating_Hours__c];

        Test.startTest();
        for(Operating_Hours__c h :Hours) {
            FacilityWorkingHoursUpdate.updateHoursRandomly(h);
        }

        update Hours;
        Test.stopTest();

        List<Operating_Hours__c> updatedHours = [SELECT Id, Opening_Time__c, Closing_Time__c FROM Operating_Hours__c];
        for (Operating_Hours__c h : updatedHours) {
            System.assertNotEquals(Time.newInstance(8, 0, 0, 0), h.Opening_Time__c);
            System.assertNotEquals(Time.newInstance(16, 0, 0, 0), h.Closing_Time__c);
        }
    }

    @isTest
    static void testBatchable(){
        List<Operating_Hours__c> Hours = [SELECT Id, Opening_Time__c, Closing_Time__c FROM Operating_Hours__c];

        Test.startTest();
        FacilityWorkingHoursUpdate batch = new FacilityWorkingHoursUpdate();
        Database.executeBatch(batch);
        Test.stopTest();

        List<Operating_Hours__c> newHours = [SELECT Id, Opening_Time__c, Closing_Time__c FROM Operating_Hours__c];

        System.assertNotEquals(Hours, newHours);
    }

    @isTest
    static void testBatchableFailure(){

        Test.startTest();
        FacilityWorkingHoursUpdate batch = new FacilityWorkingHoursUpdate();
    
        batch.isUpdateSuccessful = False;
        Database.executeBatch(batch);
        Test.stopTest();

        List<EmailMessage> sentEmails = [
                        SELECT Id, ToAddress, Subject, TextBody
                        FROM EmailMessage
                    ];

        System.assertEquals(1, sentEmails.size());
    }
}