force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Opening_Hours__c.field-meta.xml
<CustomField>
    <fullName>Opening_Hours__c</fullName>
    <label>Opening_Hours</label>
    <referenceTo>Opening_Hours__c</referenceTo>
    <relationshipLabel>Medical Facilitys</relationshipLabel>
    <relationshipName>Medical_Facilitys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/Opening_Hours__c.object-meta.xml
<CustomObject>
    <label>Opening_Hours</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Opening_Hours Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opening_Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opening_Hours__c/fields/Friday_Close__c.field-meta.xml
<CustomField>
    <fullName>Friday_Close__c</fullName>
    <label>Friday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Friday_Open__c.field-meta.xml
<CustomField>
    <fullName>Friday_Open__c</fullName>
    <label>Friday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Monday_Close__c.field-meta.xml
<CustomField>
    <fullName>Monday_Close__c</fullName>
    <label>Monday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Monday_Open__c.field-meta.xml
<CustomField>
    <fullName>Monday_Open__c</fullName>
    <label>Monday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Saturday_Close__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Close__c</fullName>
    <label>Saturday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Saturday_Open__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Open__c</fullName>
    <label>Saturday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Sunday_Close__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Close__c</fullName>
    <label>Sunday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Sunday_Open__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Open__c</fullName>
    <label>Sunday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Thursday_Close__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Close__c</fullName>
    <label>Thursday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Thursday_Open__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Open__c</fullName>
    <label>Thursday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Tuesday_Close__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Close__c</fullName>
    <label>Tuesday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Tuesday_Open__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Open__c</fullName>
    <label>Tuesday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Wednesday_Close__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Close__c</fullName>
    <label>Wednesday Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opening_Hours__c/fields/Wednesday_Open__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Open__c</fullName>
    <label>Wednesday Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/RESTMedicalFacilityHelper.cls
public with sharing virtual class RESTMedicalFacilityHelper extends RESTMedicalFacilityUtils {

}

// public with sharing virtual class RESTMedicalFacilityHelper extends RESTMedicalFacilityUtils {
//     public static void updateFacility(FacilityWrapper wrapper) {
//         Medical_Facility__c facility = [SELECT Id, Name, Address__c, Opening_Hours__c FROM Medical_Facility__c WHERE Id = :wrapper.Id LIMIT 1];

//         Opening_Hours__c opHours = [SELECT Monday_Open__c, Monday_Close__c, Tuesday_Open__c, Tuesday_Close__c,
//            Wednesday_Open__c, Wednesday_Close__c, Thursday_Open__c, Thursday_Close__c,
//            Friday_Open__c, Friday_Close__c, Saturday_Open__c, Saturday_Close__c,
//            Sunday_Open__c, Sunday_Close__c FROM Opening_Hours__c WHERE Id = :facility.Opening_Hours__c];

//         if(wrapper.name != NULL) {
//             facility.Name = wrapper.name;
//         }
        
//         if(wrapper.address != NULL) {
//             facility.Address__c = wrapper.address;
//         }

//         try {
//             updateHours(opHours, wrapper);
//         } catch (Exception e) {
//             System.debug('Exception caught: ' + e.getMessage());
//             RestContext.response.statusCode = 400;
//             RestContext.response.responseBody = Blob.valueOf(e.getMessage());
//             throw e;
//         }

//         update opHours;
//         update facility;
//     }

//     public static void updateFacilities(List<FacilityWrapper> wrappers) {
//         Set<Id> facilityIds = new Set<Id>();
    
//         for (FacilityWrapper wrapper : wrappers) {
//             facilityIds.add(wrapper.Id);
//         }
    
//         Map<Id, Medical_Facility__c> facilityMap = new Map<Id, Medical_Facility__c>([
//             SELECT Id, Name, Address__c, Opening_Hours__c FROM Medical_Facility__c WHERE Id IN :facilityIds]);

//         List<Id> opHoursIds = new List<Id>();

//         for (FacilityWrapper wrapper : wrappers) {
//             Medical_Facility__c facility = facilityMap.get(wrapper.Id);

//             opHoursIds.add(facility.Opening_Hours__c);
//         }

//         List<Opening_Hours__c> hours = 
//             [SELECT Monday_Open__c, Monday_Close__c, Tuesday_Open__c, Tuesday_Close__c,
//            Wednesday_Open__c, Wednesday_Close__c, Thursday_Open__c, Thursday_Close__c,
//            Friday_Open__c, Friday_Close__c, Saturday_Open__c, Saturday_Close__c,
//            Sunday_Open__c, Sunday_Close__c FROM Opening_Hours__c WHERE Id IN :opHoursIds];
        
    
//         Set<Medical_Facility__c> facilitiesToUpdate = new Set<Medical_Facility__c>();
//         List<Opening_Hours__c> hoursToUpdate = new List<Opening_Hours__c>();
    
//         for (Integer i = 0; i < wrappers.size(); i++) {
//             FacilityWrapper wrapper = wrappers[i];
//             Medical_Facility__c facility = facilityMap.get(wrapper.Id);
//             Opening_Hours__c opHours = hours[i];
    
//             if (facility != null) {
//                 if(wrapper.name != NULL) {
//                     facility.Name = wrapper.name;
//                     facilitiesToUpdate.add(facility);
//                 }
                
//                 if(wrapper.address != NULL) {
//                     facility.Address__c = wrapper.address;
//                     facilitiesToUpdate.add(facility);
//                 }
                
//                 try {
//                     updateHours(opHours, wrapper);
//                 } catch (Exception e) {
//                     System.debug('Exception caught: ' + e.getMessage());
//                     RestContext.response.statusCode = 400;
//                     RestContext.response.responseBody = Blob.valueOf(e.getMessage());
//                     throw e;
//                 }

//                 hoursToUpdate.add(opHours);
//             }
//         }
        
//         update hoursToUpdate;
//         update new List<Medical_Facility__c>(facilitiesToUpdate);

//         RestContext.response.statusCode = 200;
//     }
// }